[package]
name = "test_dynamic_sel"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
path = "../test_static_sel/lib.rs"

[dependencies]
objc2 = { path = "../../../objc2", default-features = false }

[features]
default = ["apple", "std"]
std = ["objc2/std"]
# Runtime
apple = ["objc2/apple"]
gnustep-1-7 = ["objc2/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "objc2/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "objc2/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "objc2/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "objc2/gnustep-2-1"]

# Hack to prevent the feature flag from being enabled in the entire project
assembly-features = []
