[package]
name = "test-assembly"
version = "0.1.0"
edition = "2021"
publish = false

repository = "https://github.com/madsmtm/objc2"
license = "MIT"

build = "build.rs"

[features]
run = ["cargo_metadata", "rustc-demangle", "regex", "lazy_static"]

[dependencies]
cargo_metadata = { version = "0.15.2", optional = true }
rustc-demangle = { version = "0.1", optional = true }
regex = { version = "1.6", optional = true }
lazy_static = { version = "1.4.0", optional = true }

[[bin]]
name = "test-assembly"
required-features = ["run"]
