framework = "AutomaticAssessmentConfiguration"
crate = "objc2-automatic-assessment-configuration"
required-crates = ["bitflags", "objc2", "objc2-foundation"]
macos = "10.15.4"
maccatalyst = "13.4"
ios = "13.4"
visionos = "1.0"
