language: rust
rust:
  - stable
  - nightly
os: osx
env:
  - IOS_ARCHS=""
matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      rust: nightly
      env: IOS_ARCHS="i386 x86_64 armv7 armv7s aarch64"
sudo: false
install: ./travis_install.sh
script: ./travis_test.sh
