[package]
name = "examples-metal"
version = "0.0.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
publish = false

[[example]]
name = "triangle"
path = "triangle/main.rs"

[[example]]
name = "default_xcode_game"
path = "default_xcode_game/main.rs"

[features]
unstable-darwin-objc = []

[dependencies]
objc2 = "0.6.2"
dispatch2 = "0.3.0"
block2 = "0.6.1"
objc2-metal = { version = "0.3.1", default-features = false, features = [
    "std",
    "objc2-core-foundation",
    "MTLAllocation",
    "MTLAccelerationStructureTypes",
    "MTLLibrary",
    "MTLRenderPipeline",
    "MTLRenderCommandEncoder",
    "MTLCommandBuffer",
    "MTLCommandEncoder",
    "MTLCommandQueue",
    "MTLPixelFormat",
    "MTLDevice",
    "MTLDrawable",
    "MTLRenderPass",
    "default" # temp
] }
objc2-metal-kit = { version = "0.3.1", default-features = false, features = [
    "std",
    "objc2-core-foundation",
    "objc2-app-kit",
    "objc2-quartz-core",
    "objc2-model-io",
    "MTKView",
    "MTKModel",
    "default" # temporary
] }
objc2-model-io = { version = "0.3.1", default-features = false, features = [
    "std",
    "MDLTypes",
    "MDLMesh",
] }
objc2-foundation = { version = "0.3.1", default-features = false, features = [
    "std",
    "NSError",
    "NSString",
    "NSDate",
    "NSNotification",
    "NSThread",
    "NSGeometry",
] }
objc2-core-foundation = { version = "0.3.1", default-features = false, features = [
    "std",
    "CFCGTypes",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.1", default-features = false, features = [
    "std",
    "NSApplication",
    "NSGraphics",
    "NSMenu",
    "NSMenuItem",
    "NSResponder",
    "NSRunningApplication",
    "NSView",
    "NSViewController",
    "NSWindow",
    "NSWindowController",
] }
