[package]
name = "test-ui"
version = "0.1.0"
edition = "2021"
publish = false

repository = "https://github.com/madsmtm/objc2"
license = "MIT"

[features]
# UI tests don't work without `Foundation` feature, but we have no way of
# specifying that, as trybuild doesn't take any arguments
default = [
    "apple",
    "std",
    "icrate/Foundation",
    "icrate/Foundation_NSString",
    "icrate/Foundation_NSMutableString",
    "icrate/Foundation_NSNotification",
    "icrate/Foundation_NSThread",
    "icrate/Foundation_NSError",
    "icrate/Foundation_NSArray",
    "icrate/Foundation_NSMutableArray",
    "icrate/Foundation_NSValue",
    "icrate/Foundation_NSSet",
    "icrate/AppKit",
    "icrate/AppKit_NSApplication",
    "objc2/unstable-msg-send-always-comma",
]
std = ["block2/std", "objc2/std", "icrate/std"]

apple = ["block2/apple", "objc2/apple", "icrate/apple"]
gnustep-1-7 = ["block2/gnustep-1-7", "objc2/gnustep-1-7", "icrate/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "block2/gnustep-1-8", "objc2/gnustep-1-8", "icrate/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "block2/gnustep-1-9", "objc2/gnustep-1-9", "icrate/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "block2/gnustep-2-0", "objc2/gnustep-2-0", "icrate/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "block2/gnustep-2-1", "objc2/gnustep-2-1", "icrate/gnustep-2-1"]

run = ["trybuild"]

[dependencies]
trybuild = { version = "1.0.72", optional = true }
block2 = { path = "../block2", default-features = false }
objc2 = { path = "../objc2", default-features = false }
icrate = { path = "../icrate", default-features = false }

[[bin]]
name = "test-ui"
required-features = ["run"]
