[package]
name = "test-ui"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Zlib OR Apache-2.0 OR MIT"

[lints]
workspace = true

[features]
# UI tests don't work without these features, but we have no way of
# specifying that, as trybuild doesn't take any arguments
default = [
    "objc2-foundation/block2",
    "objc2-foundation/NSObjCRuntime",
    "objc2-foundation/NSString",
    "objc2-foundation/NSNotification",
    "objc2-foundation/NSThread",
    "objc2-foundation/NSError",
    "objc2-foundation/NSArray",
    "objc2-foundation/NSValue",
    "objc2-foundation/NSSet",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSURLSession",
    "objc2-foundation/NSEnumerator",
    "objc2-foundation/NSDictionary",
    "objc2-core-foundation/CFBase",
    "objc2-core-foundation/CFString",
    "objc2/unstable-msg-send-always-comma",
]
run = ["trybuild"]

gnustep-1-7 = ["block2/gnustep-1-7", "objc2/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "block2/gnustep-1-8", "objc2/gnustep-1-8", "objc2-foundation/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "block2/gnustep-1-9", "objc2/gnustep-1-9", "objc2-foundation/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "block2/gnustep-2-0", "objc2/gnustep-2-0", "objc2-foundation/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "block2/gnustep-2-1", "objc2/gnustep-2-1", "objc2-foundation/gnustep-2-1"]

[dependencies]
trybuild = { version = "1.0.72", optional = true }
block2 = { path = "../block2" }
objc2 = { path = "../objc2" }
objc2-foundation = { path = "../../framework-crates/objc2-foundation", default-features = false, features = ["std"] }
objc2-core-foundation = { path = "../../framework-crates/objc2-core-foundation", default-features = false, features = ["std"] }

# To make CI work
[target.'cfg(not(target_vendor = "apple"))'.dependencies]
block2 = { path = "../block2", features = ["gnustep-1-7"] }
objc2 = { path = "../objc2", features = ["gnustep-1-7"] }
objc2-foundation = { path = "../../framework-crates/objc2-foundation", default-features = false, features = ["std", "gnustep-1-7"] }

[[bin]]
name = "test-ui"
required-features = ["run"]

[package.metadata.release]
release = false
