framework = "ObjectiveC"
crate = "objc2"
required-crates = []
link = false
skipped = true
is-library = true

macos = "10.0"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"
gnustep = true

# Both a protocol and a class, so we use Swift's naming scheme
protocol.NSObject.renamed = "NSObjectProtocol"

# Return type `oneway void`
class.NSObject.methods.release.skipped = true

# Zones aren't really supported anymore, but they were definitely a single
# object, and they very likely would need to use interior mutation (hence we
# can change the argument to be `Option<&NSZone>`).
class.NSObject.methods."allocWithZone:".arguments.0.written = false
class.NSObject.methods."allocWithZone:".arguments.0.bounds = "single"
class.NSObject.methods."copyWithZone:".arguments.0.written = false
class.NSObject.methods."copyWithZone:".arguments.0.bounds = "single"
class.NSObject.methods."mutableCopyWithZone:".arguments.0.written = false
class.NSObject.methods."mutableCopyWithZone:".arguments.0.bounds = "single"
