framework = "Contacts"
crate = "objc2-contacts"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.11"
maccatalyst = "13.0"
ios = "9.0"
watchos = "2.0"
visionos = "1.0"

# Set counterparts
class.CNContact.counterpart.mutable-subclass = "Contacts.CNMutableContact.CNMutableContact"
class.CNMutableContact.counterpart.immutable-superclass = "Contacts.CNContact.CNContact"
class.CNGroup.counterpart.mutable-subclass = "Contacts.CNMutableGroup.CNMutableGroup"
class.CNMutableGroup.counterpart.immutable-superclass = "Contacts.CNGroup.CNGroup"
class.CNPostalAddress.counterpart.mutable-subclass = "Contacts.CNMutablePostalAddress.CNMutablePostalAddress"
class.CNMutablePostalAddress.counterpart.immutable-superclass = "Contacts.CNPostalAddress.CNPostalAddress"
