framework = "__libc__"
crate = "libc"
required-crates = []
link = false
skipped = true
is-library = true

# Available everywhere
macos = "10.0"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"
gnustep = true

# HACK: Define `task_port_t` and `task_id_token_t` in the using crate
# These are simple aliases to `task_t` and `mach_port_t` respectively.
external.task_port_t.module = "__builtin__"
external.task_id_token_t.module = "__builtin__"

# Redefined by CoreFoundation with a name that makes it hard to see
# that this is `libc::malloc_zone_t`.
struct._malloc_zone_t.renamed = "malloc_zone_t"
