framework = "CoreWLAN"
crate = "objc2-core-wlan"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.6"
maccatalyst = "13.0"

external.SFAuthorization.module = "SecurityFoundation.SFAuthorization"

# Set counterparts
class.CWConfiguration.counterpart.mutable-subclass = "CoreWLAN.CWConfiguration.CWMutableConfiguration"
class.CWMutableConfiguration.counterpart.immutable-superclass = "CoreWLAN.CWConfiguration.CWConfiguration"
class.CWNetworkProfile.counterpart.mutable-subclass = "CoreWLAN.CWNetworkProfile.CWMutableNetworkProfile"
class.CWMutableNetworkProfile.counterpart.immutable-superclass = "CoreWLAN.CWNetworkProfile.CWNetworkProfile"
