framework = "MultipeerConnectivity"
crate = "objc2-multipeer-connectivity"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "7.0"
tvos = "10.0"
visionos = "1.0"
