framework = "Virtualization"
crate = "objc2-virtualization"
required-crates = ["objc2", "objc2-foundation"]
macos = "11.0"

# Needs `ether_addr_t`
class.VZMACAddress.methods."initWithEthernetAddress:".skipped = true
# Needs `ether_addr_t`
class.VZMACAddress.methods.ethernetAddress.skipped = true
# Needs `dispatch_queue_t`
class.VZVirtualMachine.methods."initWithConfiguration:queue:".skipped = true
