[features]
# Private framework functionality
#
# These functions/methods are all marked `unsafe`, since they may not always
# exist.
unstable-private = [
    "objc2-foundation/NSString",
    "objc2-foundation/NSError",
]

# TODO(breaking): Remove these workarounds.
MTLAccelerationStructureCommandEncoder = [
    "objc2-foundation/NSObject",
    "MTLAccelerationStructure",
]
MTLArgument = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSString",
    "MTLDataType",
]
MTLStageInputOutputDescriptor = [
    "objc2-foundation/NSObject",
    "MTLArgument",
]
MTLComputePipeline = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSError",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSString",
    "MTLAllocation",
]
MTLRenderPipeline = [
    "bitflags",
    "objc2-foundation/NSArray",
    "objc2-foundation/NSError",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSString",
    "MTLAllocation",
]
MTLDevice = [
    "bitflags",
    "objc2-foundation/NSArray",
    "objc2-foundation/NSBundle",
    "objc2-foundation/NSError",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSString",
    "objc2-foundation/NSURL",
    "MTLLibrary",
    "MTLResource",
    "MTLGPUAddress",
]
# Missed in v0.3.2, see <github.com/Traverse-Research/saxaboom/pull/44>
MTLBuffer = [
    "objc2-foundation/NSError",
    "objc2-foundation/NSRange",
    "objc2-foundation/NSString",
    "MTLGPUAddress",
]
