framework = "AppTrackingTransparency"
crate = "objc2-app-tracking-transparency"
required-dependencies = ["objc2-foundation"]
macos = "11.0"
maccatalyst = "14.0"
ios = "14.0"
tvos = "14.0"
visionos = "1.0"

# Workaround for header-translator not supporting definitions in umbrella header
static.AppTrackingTransparencyVersionNumber.skipped = true
static.AppTrackingTransparencyVersionString.skipped = true
